### PR TITLE
Trying out ruby-kickstart challenge

### PR DESCRIPTION
**Pull request by benji1304**
Suggested by @nikeshashar at today's pair session

### CODE REVIEW

**Comment by nikeshashar** [comment]
@benji1304 - i've recently updated our repo to remove the limitations on rspec. Have you got the latest version from our `master` branch?

**Comment by benji1304** [comment]
@nikeshashar nope, doesn't look like I have. I'll work out how to merge the updated version into my branch.

**Comment by benji1304** [comment]
@nikeshashar Am I correct in thinking this is what I need to do? 
https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by benji1304** [comment]
Did this instead. So far so good...
https://help.github.com/articles/syncing-a-fork/

**Comment by nikeshashar** [comment]
@benji1304 This seems to be working locally. I think you might need to update your local Ruby version to solve this error : https://travis-ci.org/makersacademy/ruby-kickstart/builds/359250563?utm_source=github_status&utm_medium=notification

**Comment by benji1304** [comment]
@nikeshashar is that the Travis build failing? 

I'm running
```
ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
which ruby
/usr/local/bin/ruby
```

Not sure I understand why it is failing! the build log shows (https://travis-ci.org/makersacademy/ruby-kickstart/builds/359250563#L436)  shows rvm is calling ruby 2.1.0?

**Comment by benji1304** [comment]
@nikeshashar any idea why my PR keeps failing Travis? Is it something with my local setup?

**Comment by nikeshashar** [comment]
@benji1304 I see this : https://travis-ci.org/makersacademy/ruby-kickstart/builds/361623543?utm_source=github_status&utm_medium=notification

Says there's a mismatch in the Ruby version being used.

**Comment by nikeshashar** [comment]
Also looking back at your master : https://github.com/benji1304/ruby-kickstart/blob/master/.travis.yml It seems you need to pull over the changes we've made on our repo and merge them into your branch.

**Comment by benji1304** [comment]
I'll give that another look!

**Comment by benji1304** [comment]
My .travis.yml file looks the same as the repo, but you have a recent PR where you updated it 
https://github.com/makersacademy/ruby-kickstart/pull/385/commits/e16e8760bdeb871f873508dbd1dd722e064a4f23

**Comment by benji1304** [comment]
Manually updated .travis.yml to match PR works. Now just failing due to rake errors in my code
https://travis-ci.org/makersacademy/ruby-kickstart/builds/361650354#L579

**Comment by nikeshashar** [comment]
I've just updated my PR and merged it into the master. Try it now?

**Comment by benji1304** [comment]
@nikeshashar i'm trying to work out how to merge the new master into my fork.

```
git fetch
git merge
```
or 
```
git pull
```
Say i'm already up to date
```
git checkout upstream/mastewr
```
Shows me the change I want to travis.yml, I'm just reading up on _how_ to get that change and apply to my fork!

**Comment by nikeshashar** [comment]
This article might help : https://help.github.com/articles/syncing-a-fork/. It does refer to some more advanced Github things. You can practice these at gitimmersion.com

**Comment by benji1304** [comment]
That doesn't appear to be working as it thinks i'm already up to date. If i create a local branch and checkout then I can see the travis.yml change. I then need to merge that branch into my master.

**Pull request closed without merging**
